// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SwipeService.Data;

#nullable disable

namespace SwipeService.Migrations
{
    [DbContext(typeof(SwipeContext))]
    [Migration("20260820155020_AddIsBotGenerated")]
    partial class AddIsBotGenerated
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SwipeService.Models.DailySwipeLimit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("LastSwipeAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("SwipeCount")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .HasDatabaseName("IX_DailySwipeLimit_Date");

                    b.HasIndex("UserId", "Date")
                        .IsUnique()
                        .HasDatabaseName("IX_DailySwipeLimit_UserId_Date");

                    b.ToTable("DailySwipeLimits");
                });

            modelBuilder.Entity("SwipeService.Models.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsBotGenerated")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("UnmatchedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("UnmatchedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("User1Id")
                        .HasColumnType("int");

                    b.Property<int>("User2Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("User1Id")
                        .HasDatabaseName("IX_Match_User1Id");

                    b.HasIndex("User2Id")
                        .HasDatabaseName("IX_Match_User2Id");

                    b.HasIndex("User1Id", "User2Id")
                        .IsUnique()
                        .HasDatabaseName("IX_Match_User1Id_User2Id");

                    b.ToTable("Matches", t =>
                        {
                            t.HasCheckConstraint("CK_Match_UserOrder", "User1Id < User2Id");
                        });
                });

            modelBuilder.Entity("SwipeService.Models.Profile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_Profile_UserId");

                    b.ToTable("Profiles", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("SwipeService.Models.Swipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeviceInfo")
                        .HasColumnType("longtext");

                    b.Property<string>("IdempotencyKey")
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsBotGenerated")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsLike")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("MatchId")
                        .HasColumnType("int");

                    b.Property<int>("TargetUserId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("UserLocation")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("IX_IdempotencyKey")
                        .HasFilter("[IdempotencyKey] IS NOT NULL");

                    b.HasIndex("MatchId");

                    b.HasIndex("TargetUserId")
                        .HasDatabaseName("IX_TargetUserId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_UserId");

                    b.HasIndex("UserId", "CreatedAt")
                        .HasDatabaseName("IX_Swipes_User_Created");

                    b.HasIndex("UserId", "TargetUserId")
                        .IsUnique()
                        .HasDatabaseName("IX_UserId_TargetUserId");

                    b.HasIndex("UserId", "IsLike", "CreatedAt")
                        .HasDatabaseName("IX_Swipes_User_Like_Created");

                    b.ToTable("Swipes");
                });

            modelBuilder.Entity("SwipeService.Models.SwipeBehaviorStats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AvgSwipeVelocity")
                        .HasColumnType("decimal(6,2)");

                    b.Property<DateTime?>("CooldownUntil")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CurrentConsecutiveLikes")
                        .HasColumnType("int");

                    b.Property<int>("DaysActive")
                        .HasColumnType("int");

                    b.Property<string>("FlagReason")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("FlaggedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("LastCalculatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("LastSwipeAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PeakSwipeStreak")
                        .HasColumnType("int");

                    b.Property<int>("RapidSwipeCount")
                        .HasColumnType("int");

                    b.Property<decimal>("RightSwipeRatio")
                        .HasColumnType("decimal(5,4)");

                    b.Property<decimal>("SwipeTrustScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(100m);

                    b.Property<int>("TotalLikes")
                        .HasColumnType("int");

                    b.Property<int>("TotalPasses")
                        .HasColumnType("int");

                    b.Property<int>("TotalSwipes")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SwipeTrustScore")
                        .HasDatabaseName("IX_SwipeBehaviorStats_TrustScore");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_SwipeBehaviorStats_UserId");

                    b.ToTable("SwipeBehaviorStats");
                });

            modelBuilder.Entity("SwipeService.Models.UserProfileMapping", b =>
                {
                    b.Property<int>("ProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ProfileId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.HasKey("ProfileId");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_UserProfileMapping_UserId");

                    b.ToTable("UserProfileMappings");
                });

            modelBuilder.Entity("SwipeService.Models.Swipe", b =>
                {
                    b.HasOne("SwipeService.Models.Match", "Match")
                        .WithMany("Swipes")
                        .HasForeignKey("MatchId");

                    b.Navigation("Match");
                });

            modelBuilder.Entity("SwipeService.Models.Match", b =>
                {
                    b.Navigation("Swipes");
                });
#pragma warning restore 612, 618
        }
    }
}
